import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c2c1ff',
        'on-primary-fixed': '#151449',
        'on-primary-fixed-variant': '#414177',
        'secondary-fixed': '#b5eedd',
        'secondary-fixed-dim': '#9ad2c2',
        'on-secondary-fixed': '#00201a',
        'on-secondary-fixed-variant': '#164f43',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#e4bfa6',
        'on-tertiary-fixed': '#2b1707',
        'on-tertiary-fixed-variant': '#5b412e',
        'surface-bright': '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'surface-tint': '#595990',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'inverse-primary': '#c2c1ff',
        'outline-variant': '#c8c5d0',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#47464f',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-background': '#1c1b1b',
        'on-primary-container': '#3a3a6f',
        'on-secondary-container': '#386e61',
        'on-tertiary-container': '#543b28',
        'on-error-container': '#93000a',
        'primary-container': '#a7a6e3',
        'secondary-container': '#b5eedd',
        'tertiary-container': '#c8a58d',
        'error-container': '#ffdad6',
        primary: '#595990',
        secondary: '#31685b',
        tertiary: '#755844',
        error: '#ba1a1a',
        outline: '#777680',
        surface: '#fcf9f8',
        background: '#fcf9f8',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '12px',
        'stack-md': '24px',
        'stack-lg': '48px',
        unit: '8px',
        gutter: '32px',
        'container-max': '1280px',
        'section-padding': '120px',
      },
      fontFamily: {
        body: ['var(--font-manrope)', 'sans-serif'],
        display: ['var(--font-manrope)', 'sans-serif'],
        headline: ['var(--font-manrope)', 'sans-serif'],
        h1: ['var(--font-manrope)', 'sans-serif'],
        h2: ['var(--font-manrope)', 'sans-serif'],
        h3: ['var(--font-manrope)', 'sans-serif'],
        'body-lg': ['var(--font-manrope)', 'sans-serif'],
        'body-md': ['var(--font-manrope)', 'sans-serif'],
        'label-caps': ['var(--font-manrope)', 'sans-serif'],
        label: ['var(--font-manrope)', 'sans-serif'],
      },
      fontSize: {
        display: ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}

export default config
